config/routes.rb
Rails.application.routes.draw do
  root 'sesg_page#home'
  
  resources :volunteers
  resources :events
  resources :tasks , only: [:create, :edit, :update, :destroy, :show]
  resources :registers, only: [:create, :destroy]
  resources :notifications, only: [:create, :destroy]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  get     'about'                   => 'sesg_page#about'
  get     'contact'                 => 'sesg_page#contact'
  get     'signup'                  => 'volunteers#new'
  get     'login'                   => 'sessions#new'
  get     'tasks/new/:event_id'     => 'tasks#new'
  get     'help'                    => 'sesg_page#help'
  get     'score_board/:id'         => 'volunteers#score_board'
  get     'admin_history'           => 'admin_histories#new'
  get     'search'                  => 'volunteers#search'
  get     'change_locale/:lang'     => 'sessions#change_locale'
  
  
  post    'reset/volunteers/:id'    => 'volunteers#reset'
  post    'assess'                  => 'registers#update_all'
  post    'appoint/volunteers/:id'  => 'volunteers#appoint'
  post    'login'                   => 'sessions#create'
  
  delete  'logout'                  => 'sessions#destroy'
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :event
  has_many :registers, dependent: :destroy
  has_many :volunteers, through: :registers
  has_one :restriction, dependent: :destroy
  validates :name,  presence: true, length: { maximum: 50 }
  default_scope -> { order(created_at: :desc) }
  validates :start_time, :end_time, :awn, :awon, :lwn, :lwon, :ontime, :bonus, :minus, :max_volunteer_number, presence: true
  validate :start_time_before_end_time
  
  def start_time_before_end_time
    if !start_time.nil? && !end_time.nil?
      if start_time > end_time
        errors.add(:start_time, "Must Occured Before End Time")
      end
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # Filters
  before_action :logged_in_volunteer
  before_action :is_admin_or_core,     only: [:create, :destroy, :edit, :update, :new]
  before_action :check_task, only: [:show, :edit, :update, :destroy]
  
  # Show
  def show
    @task = Task.find(params[:id])
    @register = Register.new
    @registers = @task.registers
    
    restricts = @task.restriction
    @isRestricted = true
    if !restricts.nil?
      if restricts.task_restrict == "" && restricts.tag == ""
        @isRestricted = false
      elsif !restricts.task_restrict == "" && !restricts.tag == ""
        regs = current_volunteer.registers
        regs.each do |re|
          if re.task_id == restricts.task_restrict && re.tag != restricts.tag
            @isRestricted = false
            break
          end
        end
      elsif restricts.task_restrict == ""
        regs = current_volunteer.registers
        @isRestricted = false
        regs.each do |re|
          if re.tag == restricts.tag
            @isRestricted = true
            break
          end
        end
      elsif restricts.tag == ""
        tasks = current_volunteer.tasks
        if tasks.include?(Task.find(restricts.task_restrict))
          @isRestricted = false
        end
      end
    else
      @isRestricted = false
    end
  end
  
  # Add
  def new
    @event = Event.find(params[:event_id])
    @task = Task.new
  end
  
  def create
    local_params = task_params.clone
    local_params[:current_volunteer_number] = 0
    local_params[:current_backup] = 0
    @task = Task.new(local_params)
    if @task.save
      flash[:success] = "Task Created!"
      if !(params[:task][:restrictions][:restriction_task] == nil && params[:task][:restrictions][:restriction_tag] == nil)
        Restriction.create(:task_id => @task.id.to_s, :tag => params[:task][:restrictions][:restriction_tag].to_s,
                                :task_restrict => params[:task][:restrictions][:restriction_task].to_s)
      end
      if current_volunteer.admin?
        AdminHistory.create(:content => "Created new task: #{@task.name}")
      else
        AdminHistory.create(:content => "#{current_volunteer.name} created new task: #{@task.name}")
      end
      redirect_to @task
    else
      flash[:danger] = "Some fields are missing"
      redirect_to "/tasks/new/#{task_params[:event_id]}"
    end
  end
  
  # Edit
  def edit
    @events = Event.all
    @task = Task.find(params[:id])
  end
  
  def update
    @events = Event.all
    @task = Task.find(params[:id])
    if @task.update_attributes(task_params)
      flash[:success] = "Task Updated!"
      vols = @task.volunteers
      vols_id = ""
      vols.each do |v|
        vols_id += v.id.to_s + ";"
      end
      evt = Event.find(@task[:event_id])
      if current_volunteer.admin?
        AdminHistory.create(:content => "Updated a task: #{evt.name} #{@task.name}")
      else
        AdminHistory.create(:content => "#{current_volunteer.name} updated a task: #{evt.name} #{@task.name}")
      end
      Notification.create(:sender_id => "SESG", :receiver_id => vols_id,
                          :event_id => @task.event_id.to_s,
                          :content => "Task #{@task.name} have been updated.")
      redirect_to @task
    else
      render 'edit'
    end
  end
  
  # Delete
  def destroy
    task = Task.find(params[:id])
    vols = task.volunteers
    vols_id = ""
    vols.each do |v|
      vols_id += v.id.to_s + ";"
    end
    evt = Event.find(task[:event_id])
    if current_volunteer.admin?
      AdminHistory.create(:content => "Deleted a task: #{evt.name} #{task.name}")
    else
      AdminHistory.create(:content => "#{current_volunteer.name} deleted a task: #{evt.name} #{task.name}")
    end
    Notification.create(:sender_id => "SESG", :receiver_id => vols_id,
                        :event_id => task.event_id.to_s,
                        :content => "Task #{task.name} have been cancelled.")
    task.destroy
    flash[:success] = "Task Deleted!"
    redirect_to events_path
  end
  
  private

    def task_params
      params.require(:task).permit(:name, :description, :start_time, :end_time,
                                   :awn, :awon,:lwn, :lwon, :ontime, :bonus, 
                                   :minus, :event_id, :task_type, 
                                   :max_volunteer_number, :max_backup)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def check_task
    t = Task.find_by(:id => params[:id])
    if t.nil?
      flash[:danger] = "No task with that ID found"
      redirect_to events_path
    end
  end
end

app/views/tasks/edit.html.erb
<% provide(:title, "Edit Task") %>
<div class="jumbotron">
  <h1><%= I18n.t('update_task') %></h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@task) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        
        <%= f.label I18n.t('name') %>
        <%= f.text_field :name, class: 'form-control' %>
  
        <%= f.label I18n.t('desc') %>
        <%= f.text_field :description, class: 'form-control' %>
        
        <%= f.label I18n.t('task_type') %>
        <%= f.select(:task_type, "<option value='true'>Volunteer</option><option value='false'>Core</option>".html_safe) %>
        
        <%= f.label :max_volunteer_number, I18n.t('vol_num') %>
        <%= f.number_field :max_volunteer_number, min: 0, class: 'form-control' %>
        
        <%= f.label :max_backup, I18n.t('backup_num') %>
        <%= f.number_field :max_backup, min: 0, class: 'form-control' %>
  
        <%= f.label I18n.t('start') %>
        <%= f.datetime_select(:start_time, :order => [:month, :day, :year, :hour, :minute], start_year: @task.start_time.year - 10, end_year: @task.start_time.year + 10, with_css_classes: true, time_separator: "", datetime_separator: "") %>
        
        <%= f.label I18n.t('end') %>
        <%= f.datetime_select(:end_time, :order => [:month, :day, :year, :hour, :minute], start_year: @task.end_time.year - 10, end_year: @task.end_time.year + 10, with_css_classes: true, time_separator: "", datetime_separator: "") %>
        
        <%= f.label I18n.t('associated_event') %>
        <%= f.collection_select(:event_id, @events, :id, :name) %>
        
        <%= f.label I18n.t('assign_point') %>
        <ul>
          <li><%= f.label "Absent with notice" %><%= f.number_field :awn, class: 'form-control', max: 0 %></li>
          <li><%= f.label "Absent without notice" %><%= f.number_field :awon, class: 'form-control', max: 0 %></li>
          <li><%= f.label "Late with notice" %><%= f.number_field :lwn, class: 'form-control', max: 0 %></li>
          <li><%= f.label "Late without notice" %><%= f.number_field :lwon, class: 'form-control', max: 0 %></li>
          <li><%= f.label "On time" %><%= f.number_field :ontime, class: 'form-control', min: 0 %></li>
          <li><%= f.label :bonus %><%= f.number_field :bonus, class: 'form-control', min: 0 %></li>
          <li><%= f.label :minus %><%= f.number_field :minus, class: 'form-control', max: 0 %></li>
        </ul>
        <%= f.submit I18n.t('update'), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<% provide(:title, "Add Task") %>
<div class="jumbotron">
  <h1><%= I18n.t('create_task') %></h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@task) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        
        <%= f.label I18n.t('name') %>
        <%= f.text_field :name, class: 'form-control' %>
  
        <%= f.label I18n.t('desc') %>
        <%= f.text_field :description, class: 'form-control' %>
        
        <%= f.label I18n.t('associated_event') %> <br><%= @event.name %><br><br>
        <%= f.hidden_field :event_id, value: @event.id %>
        
        <%= f.label I18n.t('task_type') %>
        <%= f.select(:task_type, "<option value='true'>Volunteer</option><option value='false'>Core</option>".html_safe) %>
  
        <%= f.label :max_volunteer_number, I18n.t('vol_num') %>
        <%= f.number_field :max_volunteer_number, min: 0, class: 'form-control' %>
        
        <%= f.label :max_backup, I18n.t('backup_num') %>
        <%= f.number_field :max_backup, min: 0, class: 'form-control' %>
        
        <%= f.label I18n.t('start') %>
        <%= f.datetime_select(:start_time, :order => [:month, :day, :year, :hour, :minute], start_year: Date.today.year - 10, end_year: Date.today.year + 10, with_css_classes: true, time_separator: "", datetime_separator: "", default: @event.start_date) %>
        
        <%= f.label I18n.t('end') %>
        <%= f.datetime_select(:end_time, :order => [:month, :day, :year, :hour, :minute], start_year: Date.today.year - 10, end_year: Date.today.year + 10, with_css_classes: true, time_separator: "", datetime_separator: "", default: @event.end_date) %>
        
        <%= f.label I18n.t('assign_point') %>
        <ul>
          <li><%= f.label "Absent with notice" %><%= f.number_field :awn, class: 'form-control', max: 0 %></li>
          <li><%= f.label "Absent without notice" %><%= f.number_field :awon, class: 'form-control', max: 0 %></li>
          <li><%= f.label "Late with notice" %><%= f.number_field :lwn, class: 'form-control', max: 0 %></li>
          <li><%= f.label "Late without notice" %><%= f.number_field :lwon, class: 'form-control', max: 0 %></li>
          <li><%= f.label "On time" %><%= f.number_field :ontime, class: 'form-control', min: 0 %></li>
          <li><%= f.label :bonus %><%= f.number_field :bonus, class: 'form-control', min: 0 %></li>
          <li><%= f.label :minus %><%= f.number_field :minus, class: 'form-control', max: 0 %></li>
        </ul>
        
        <%= f.fields_for :restrictions do |fi| %>
          <%= fi.label I18n.t('restriction') %><br>
          <%= fi.label I18n.t('task') %>
          <% tasks = Task.all %>
          <%= fi.select(:restriction_task, options_from_collection_for_select(tasks, 'id', 'name'), { include_blank: true }) %>
          <%= fi.label I18n.t('tags') %>
          <%= fi.select(:restriction_tag, options_for_select( [["Absent with notice","awn"],
                                                          ["Absent without notice","awon"],
                                                          ["Late with notice","lwn"],
                                                          ["Late without notice","lwon"],
                                                          ["On time","ontime"],
                                                          ["Bonus","bonus"],
                                                          ["Minus","minus"]] ), { include_blank: true }) %>
        <% end %>
        <%= f.submit I18n.t('create'), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<% provide(:title, @task.name) %>
<div class="container">
<div class="jumbotron row">
  <aside class=".col-xs-6 .col-md-4">
    <section class="info">
      <h1>
        <%= @task.name %>
      </h1>
      <% if current_volunteer.admin? || current_volunteer.core? %>
        <%= link_to I18n.t('delete'), @task, method: :delete,
                                      data: { confirm: "You sure?" }, class: "btn btn-xs btn-info" %>
        <%= link_to I18n.t('edit'), edit_task_path(@task), class: "btn btn-xs btn-info" %>
      <% end %>
      <br>
      <h2>
        <%= @task.description %><br>
        <%= I18n.t('task_id') %>: <%= @task.id %><br>
        <% if current_volunteer.admin? || current_volunteer.core? %>
          <%= I18n.t('task_type') %>
          <% if @task.task_type? %>
            Volunteer.
          <% else %>
            Core Member.
          <% end %><br>
        <% end %>
        <%= I18n.t('events') %>: <%= link_to @task.event.name, @task.event %><br>
        <% if @task.start_time.to_date() == @task.end_time.to_date() %>
          <%= I18n.t('on1') %> <%= @task.start_time.to_date().to_formatted_s(:long) %>.
        <% else %>
          <%= I18n.t('from') %> <%= @task.start_time.to_date().to_formatted_s(:long) %> <%= I18n.t('to') %> <%= @task.end_time.to_date().to_formatted_s(:long) %>.
        <% end %>
        <br>
        <%= I18n.t('status') %>: <% if !@task.start_time.past? %>
                  <%= I18n.t('recruit') %>
                <% else %>
                  <% if !@task.end_time.past? %>
                    <%= I18n.t('ongoing') %>
                  <% else %>
                    <%= I18n.t('over') %>
                  <% end %>
                <% end %>
        <br>
        <% if @task.max_volunteer_number == @task.current_volunteer_number %>
          <% if @task.max_backup == @task.current_backup %>
            <%= I18n.t("slot_full") %>
          <% else %>
            <% if session[:locale] == "en" %>
              <%= pluralize(@task.max_backup-@task.current_backup, I18n.t("need_backup")) %> needed.
            <% else %>
              Cần <%= @task.max_backup-@task.current_backup %> <%= I18n.t("need_backup") %>.
            <% end %>
          <% end %>
        <% else %>
          <% if session[:locale] == "en" %>
              <%= pluralize(@task.max_volunteer_number - @task.current_volunteer_number, I18n.t("need_vol")) %> needed.
            <% else %>
              Cần <%= @task.max_volunteer_number - @task.current_volunteer_number %> <%= I18n.t("need_vol") %>.
            <% end %>
        <% end %>
      </h2>
      
      <h2>
      <% if !current_volunteer.admin? %>
        <% if !@task.volunteers.include?(current_volunteer) && @task.max_volunteer_number != @task.current_volunteer_number && !@isRestricted %> 
          <% if (@task.task_type? && !current_volunteer.core?) || (!@task.task_type? && current_volunteer.core?) %>
            <%= form_for(@register) do |f| %>
              <%= f.hidden_field :task_id, value: @task.id %>
              <%= f.hidden_field :volunteer_id, value: current_volunteer.id %>
              <%= f.hidden_field :backup, value: false %>
              <%= f.submit I18n.t('register'), class: "btn btn-primary" %>
            <% end %>
          <% else %>
            You are not allowed to register for this task.
          <% end %>
        <% elsif @task.max_volunteer_number == @task.current_volunteer_number && !@isRestricted && @task.max_backup != @task.current_backup && !@task.volunteers.include?(current_volunteer) %>
          <%= form_for(@register) do |f| %>
            <%= f.hidden_field :task_id, value: @task.id %>
            <%= f.hidden_field :volunteer_id, value: current_volunteer.id %>
            <%= f.hidden_field :backup, value: true %>
            <%= f.submit I18n.t('register_backup'), class: "btn btn-primary" %>
          <% end %>
        <% elsif @isRestricted %>
          <%= I18n.t('not_allowed') %>
        <% elsif @task.volunteers.include?(current_volunteer) %>
           <%= I18n.t('register_already') %>
        <% end %>
      <% end %>
      </h2>
      
      <% if !current_volunteer.admin? %>
        <h2>
        <% if @task.volunteers.include?(current_volunteer) %>
          <% r = Register.find_by(task: @task, volunteer: current_volunteer) %>
          <% if !r.backup? %>
            <% if !r[:tag].nil? %>
              <%= I18n.t('receive_tag', t: tag_name(Register.find_by(task: @task, volunteer: current_volunteer)[:tag])) %>
            <% else %>
              <%= I18n.t('pending') %>
            <% end %>
          <% end %>
        <% end %>
        </h2>
      <% end %>
      
      <p>
        <% if @registers.any? %>
          <h1><%= I18n.t('vol_list') %></h1>
          <ul>
          <% @registers.each do |re| %>
            <% vol = Volunteer.find(re[:volunteer_id]) %>
            <li>
              <h3>
                <%= image_tag vol.image_link, height: '25' %>
                <%= vol.name %> - <% if current_volunteer.admin? || current_volunteer.core? %><%= vol.email %>:<% end %>
                <% if re.backup? %>
                  <%= I18n.t('backup') %>.
                <% else %>
                  <%= I18n.t('official') %>.
                  <% if current_volunteer.admin? %>
                    <%= link_to I18n.t('delete'), re, method: :delete,
                                      data: { confirm: "You sure?" }, class: "btn btn-xs btn-info" %>
                  <% end %>
                <% end %>
              </h3>
            </li>
          <% end %>
          </ul>
        <% end %>
      </p>
      
      <% if current_volunteer.admin? || current_volunteer.core? %>
        <h2>
        <% if @task.start_time < DateTime.current && @registers.any? %>
          <h1><%= I18n.t('assess_table') %></h1>
          <%= form_for :register, :url => assess_path do |f| %>
            <% @registers.each do |re| %>
              <% if !re.backup? %>
                <%= f.fields_for "reg[]", re do |r| %>
                  <%= r.hidden_field :register_id, value: re.id %>
                  <%= r.hidden_field :task_id, value: @task.id %>
                  <h3><%= "#{Volunteer.find(re.volunteer_id).name}".html_safe %>
                  <% if re.tag.nil? %>
                    <%= r.select(:tag, options_for_select( [["Absent with notice","awn"],
                                                            ["Absent without notice","awon"],
                                                            ["Late with notice","lwn"],
                                                            ["Late without notice","lwon"],
                                                            ["On time","ontime"],
                                                            ["Bonus","bonus"],
                                                            ["Minus","minus"]]),{ include_blank: true }) %>
                  <% else %>
                    <%= r.select(:tag, options_for_select( [["Absent with notice","awn"],
                                                            ["Absent without notice","awon"],
                                                            ["Late with notice","lwn"],
                                                            ["Late without notice","lwon"],
                                                            ["On time","ontime"],
                                                            ["Bonus","bonus"],
                                                            ["Minus","minus"]],
                                                            :selected => re.tag.to_s)) %>
                  <% end %>
                  </h3>
                <% end %>
              <% end %>
            <% end %>
            <%= f.submit I18n.t("assess"), class: "btn btn-primary" %>
          <% end %>
        </h2>
        <% end %>
      <% end %>
    </section>
  </aside>
</div>
</div>