config/routes.rb
Rails.application.routes.draw do
  root 'sesg_page#home'
  
  resources :volunteers
  resources :events
  resources :tasks , only: [:create, :edit, :update, :destroy, :show]
  resources :registers, only: [:create, :destroy]
  resources :notifications, only: [:create, :destroy]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  get     'about'                   => 'sesg_page#about'
  get     'contact'                 => 'sesg_page#contact'
  get     'signup'                  => 'volunteers#new'
  get     'login'                   => 'sessions#new'
  get     'tasks/new/:event_id'     => 'tasks#new'
  get     'help'                    => 'sesg_page#help'
  get     'score_board/:id'         => 'volunteers#score_board'
  get     'admin_history'           => 'admin_histories#new'
  get     'search'                  => 'volunteers#search'
  get     'change_locale/:lang'     => 'sessions#change_locale'
  
  
  post    'reset/volunteers/:id'    => 'volunteers#reset'
  post    'assess'                  => 'registers#update_all'
  post    'appoint/volunteers/:id'  => 'volunteers#appoint'
  post    'login'                   => 'sessions#create'
  
  delete  'logout'                  => 'sessions#destroy'
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  validates :name,  presence: true, length: { maximum: 50 }
  default_scope -> { order(created_at: :desc) }
  validates :start_date, :end_date, presence: true
  validate :start_date_before_end_date
  
  def start_date_before_end_date
    if !start_date.nil? && !end_date.nil?
      if start_date > end_date
        errors.add(:start_date, "Must Occured Before End Date")
      end
    end
  end
  
  # Enable filterrific to search
  filterrific(
    default_filter_params: { sorted_by: 'created_at_desc', current: 'all' },
    available_filters: [
      :search_query,
      :sorted_by,
      :current,
      :with_start_date_gte,
      :with_start_date_lt
    ]
  )
  
  # Define scopes
  scope :search_query, lambda { |query|
    return nil  if query.blank?
    terms = query.downcase.split(/\s+/)
    # replace "*" with "%" for wildcard searches,
    # append '%', remove duplicate '%'s
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    num_or_conditions = 1
    where(
      terms.map {
        or_clauses = [
          "LOWER(events.name) LIKE ?",
        ].join(' OR ')
        "(#{ or_clauses })"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conditions }.flatten
    )
  }
  
  scope :sorted_by, lambda { |sort_option|
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^created_at_/
      order("events.created_at #{ direction }")
    when /^name_/
      order("LOWER(events.name) #{ direction }")
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }
  
  scope :current, lambda { |current_date|
    case current_date
    when 'all'
    
    when 'available'
      where(['events.start_date >= ? AND events.end_date >= ?', current_date, current_date])
      where(['events.start_date <= ? AND events.end_date >= ?', current_date, current_date])
    when 'past'
      where(['events.start_date <= ? AND events.end_date <= ?', current_date, current_date])
    else
      
    end
  }
  
  
  scope :with_start_date_gte, lambda { |ref_date|
    where('events.start_date >= ?', ref_date)
  }
  
  scope :with_start_date_lt, lambda { |ref_date|
    where('events.start_date < ?', ref_date)
  }
  
  def self.options_for_sorted_by
    [
      ['Name (A-Z)', 'name_asc'],
      ['Date Created (Newest First)', 'created_at_desc'],
      ['Date Created (Oldest First)', 'created_at_asc'],
    ]
  end
  
  def self.options_for_current
    [
      ['All', 'all'],
      ['Past', 'past'],
      ['Available', 'available'],
    ]
  end

  def decorated_start_date
    start_date.to_date.to_s(:long)
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # Filters
  before_action :logged_in_volunteer, only: [:index]
  before_action :admin_volunteer,     only: [:create, :destroy, :edit, :update, :new]
  before_action :check_event, only: [:show, :edit, :update, :destroy]
  
  # Show
  def index
    @filterrific = initialize_filterrific(
      Event,
      params[:filterrific],
      :select_options => {
        sorted_by: Event.options_for_sorted_by,
        current: Event.options_for_current,
      }
    ) or return
    @events = @filterrific.find.page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
    
    # @task = Task.new
    # @events = Event.paginate(page: params[:page])
  end
  
  def show
    @event = Event.find(params[:id])
    @max = 0
    @current = 0
    if @event.tasks.any?
      @event.tasks.each do |t| 
        @max += t.max_volunteer_number + t.max_backup
        @current += t.current_volunteer_number + t.current_backup
      end
    end
  end
  
  # Add
  def new
    @event = Event.new
  end
  
  def create
    local_params = event_params.clone
    local_params["start_date(4i)"] = "0"
    local_params["end_date(4i)"] = "23"
    local_params["start_date(5i)"] = "0"
    local_params["end_date(5i)"] = "59"
    @event = Event.new(local_params)
    if @event.save
      flash[:success] = "Event Created!"
      AdminHistory.create(:content => "Created a new event: #{@event.name}, ID: #{@event.id}")
      Notification.create(:sender_id => "SESG", :receiver_id => "all",
                            :event_id => @event.id.to_s,
                            :content => "Event #{@event.name} is recruiting.")
      
      redirect_to @event
    else
      render 'new'
    end
  end
  # Edit
  def edit
    @event = Event.find(params[:id])
  end
  
  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:success] = "Event Updated!"
      AdminHistory.create(:content => "Edited an event: #{@event.name}, ID: #{@event.id}")
      redirect_to @event
    else
      render 'edit'
    end
  end
    
  # Delete
  def destroy
    event = Event.find_by(:id => params[:id])
    AdminHistory.create(:content => "Deleted an event: #{event.name}, ID: #{event.id}")
    Notification.create(:sender_id => "SESG", :receiver_id => "all",
                        :event_id => event.id.to_s,
                        :content => "Event #{event.name} has been cancelled.")
    event.destroy
    flash[:success] = "Event Deleted!"
    redirect_to events_url
  end
  
  private

    def event_params
      params.require(:event).permit(:name, :description, :start_date,
                                   :end_date, :image_link)
    end
end

app/helpers/events_helper.rb
module EventsHelper
  def check_event
    v = Event.find_by(:id => params[:id])
    if v.nil?
      flash[:danger] = "No event with that ID found"
      redirect_to events_path
    end
  end
end

app/views/events/_event.html.erb
<li>
  <%= link_to event.name, event %>
   | Status: <% if !event.start_date.past? %>
                  Recruiting.
                <% else %>
                  <% if !event.end_date.past? %>
                    Ongoing.
                  <% else %>
                    Over.
                  <% end %>
                <% end %>
  <div class="volindex">
  <% if current_volunteer.admin? %>
    <%= link_to I18n.t('delete'), event, method: :delete,
                            data: { confirm: "You sure?" }, class: "btn btn-xs btn-info" %>
    <%= link_to I18n.t('edit'), edit_event_path(event), class: "btn btn-xs btn-info" %>
    <%= link_to I18n.t('add_task'), "tasks/new/#{event.id}", class: "btn btn-xs btn-info" %>
  <% end %>
  </div>
  <br>
</li>

app/views/events/_list.html.haml
.well.well-small
  .pull-right{ :'data-position' => 'bottom', :'data-intro' => 'Reset the filter settings to defaults.' }
    = link_to "Reset filters", reset_filterrific_url, :class => 'btn btn-default btn-sm'
  = page_entries_info events, :model => 'event'
  = render_filterrific_spinner

%table.table
  %tr
    %th= I18n.t('name')
    %th= I18n.t('start')
    %th= I18n.t('end')
    - if current_volunteer.admin?
      %th{:colspan => 3}= I18n.t('options')
      
  - events.each do |event|
    %tr
      %td= link_to event.name, event
      %td= event.start_date.to_date.to_s(:long)
      %td= event.end_date.to_date.to_s(:long)
      - if current_volunteer.admin?
        %td= link_to I18n.t('delete'), event, method: :delete,
                          data: { confirm: "You sure?" }, class: "btn btn-xs btn-info"
        %td= link_to I18n.t('edit'), edit_event_path(event), class: "btn btn-xs btn-info"
        %td= link_to I18n.t('add_task'), "tasks/new/#{event.id}", class: "btn btn-xs btn-info"
      - else
        %td
        %td
        %td
        %td
        %td
       
.chardin_box{ :'data-position' => 'right', :'data-intro' => "List of found events." }
  = will_paginate @events, renderer: BootstrapPagination::Rails

app/views/events/edit.html.erb
<% provide(:title, "Edit Event") %>
<div class="jumbotron">
  <h1><%= I18n.t("update_event") %></h1>
  
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@event) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        
        <%= f.label I18n.t('name') %>
        <%= f.text_field :name, class: 'form-control' %>
  
        <%= f.label I18n.t('desc') %>
        <%= f.cktext_area :description, :class => 'form-control', :ckeditor => {:language => 'en'} %>
  
        <%= f.label I18n.t("start") %>
        <%= f.date_select(:start_date, :order => [:month, :day, :year], start_year: @event.start_date.year - 10, end_year: @event.start_date.year + 10, with_css_classes: true) %>
        
        <%= f.label I18n.t("end") %>
        <%= f.date_select(:end_date, :order => [:month, :day, :year], start_year: @event.start_date.year - 10, end_year: @event.start_date.year + 10, with_css_classes: true) %>
  
        <%= f.submit I18n.t("submit"), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/index.html.haml
.jumbotron
  .page-header{}
    %h1.chardin_box{ :'data-position' => 'right', :'data-intro' => 'Filter and sort events. Click anywhere to remove the overlay.' }
      = I18n.t('events')
    - if current_volunteer.admin?
      = link_to I18n.t('create_event'), 
                new_event_path, 
                :class => "btn btn-sm btn-primary",
                :style => 'margin: 0 0 15px 20px;'
                
    = link_to I18n.t('click_me'),
              "#",
              :id => "overlayTrigger",
              :class => 'btn btn-primary btn-lg',
              :style => 'margin: 0 0 15px 20px;'
  
  .well
    = form_for_filterrific @filterrific do |f|
      .row
        .col-md-4
          .form-group.chardin_box{ :'data-position' => 'bottom', :'data-intro' => 'Search by name' }
            %label= I18n.t('search')
            = f.text_field :search_query, 
                           :class => 'filterrific-periodically-observed form-control',
                           :size => 50
        .col-md-2
          .form-group.chardin_box{ :'data-position' => 'bottom', :'data-intro' => 'Filter by Registration Date.' }
            %label= I18n.t('created_after')
            = f.text_field :with_start_date_gte,
                           :class => 'js-datepicker form-control'
        .col-md-2
          .form-group.chardin_box{ :'data-position' => 'bottom', :'data-intro' => 'Filter by Registration Date.' }
            %label= I18n.t('created_before')
            = f.text_field :with_start_date_lt,
                           :class => 'js-datepicker form-control'
        
        .col-md-2
          .form-group.chardin_box{ :'data-position' => 'top', :'data-intro' => 'Change the sorting.' }
            %label= I18n.t('sorted_by')
            = f.select :sorted_by,
                       @filterrific.select_options[:sorted_by],
                       {},
                       { :class => 'form-control' }
                       
        .col-md-2
          .form-group.chardin_box{ :'data-position' => 'top', :'data-intro' => 'Display Option.' }
            %label= I18n.t('display')
            = f.select :current,
                       @filterrific.select_options[:current],
                       {},
                       { :class => 'form-control' }
      
  
  #results
    = render :partial => 'events/list',
             :locals => { :events => @events }

:javascript
  $('.js-datepicker').datepicker();
  $('#overlayTrigger').click(function(event) {
    event.preventDefault();
    $('body').chardinJs('start');
  });

app/views/events/index.js.erb
<% js = escape_javascript(
  render(
    :partial => 'events/list',
    :locals => { :events => @events }
  )
) %>
$("#results").html("<%= js %>");

app/views/events/new.html.erb
<% provide(:title, "Create Event") %>
<div class="jumbotron">
  <h1><%= I18n.t('create_event') %></h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@event) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        
        <%= f.label I18n.t('name') %>
        <%= f.text_field :name, class: 'form-control' %>
  
        <%= f.label I18n.t('desc') %>
        <%= f.cktext_area :description, :class => 'form-control', :ckeditor => {:language => 'en'} %>
  
        <%= f.label I18n.t('start') %>
        <%= f.date_select(:start_date, :order => [:month, :day, :year, :hour, :minute], start_year: Date.today.year - 10, end_year: Date.today.year + 10, with_css_classes: true, datetime_separator: "") %>
        
        <%= f.label I18n.t('end') %>
        <%= f.date_select(:end_date, :order => [:month, :day, :year, :hour, :minute], start_year: Date.today.year - 10, end_year: Date.today.year + 10, with_css_classes: true, datetime_separator: "") %>
  
  
        <%= f.submit I18n.t('create'), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<% provide(:title, @event.name) %>
<div class="container">
<div class="jumbotron row">
  <aside class=".col-xs-6 .col-md-4">
    <section class="event_info">
      <h1>
        <%= @event.name %>
      </h1>
      <% if current_volunteer.admin? || current_volunteer.core? %>
        <br>
        <%= link_to I18n.t('delete'), @event, method: :delete,
                                  data: { confirm: "You sure?" }, class: "btn btn-xs btn-info" %>
        <%= link_to I18n.t('edit'), edit_event_path(@event), class: "btn btn-xs btn-info" %>
        <%= link_to I18n.t('add_task'), "/tasks/new/#{@event.id}", class: "btn btn-xs btn-info" %>
        <br>
      <% end %>
      <br>
      <h2>
        <%= @event.description.html_safe %><br>
        <% if @event.start_date.to_date() == @event.end_date.to_date() %>
          <%= I18n.t('on1') %> <%= @event.start_date.to_date().to_formatted_s(:long) %>.
        <% else %>
          <%= I18n.t('from') %> <%= @event.start_date.to_date().to_formatted_s(:long) %> <%= I18n.t('to') %> <%= @event.end_date.to_date().to_formatted_s(:long) %>.
        <% end %>
        <br>
        <%= I18n.t('status') %>: <% if !@event.start_date.past? %>
                  <%= I18n.t('recruit') %>.
                <% else %>
                  <% if !@event.end_date.past? %>
                    <%= I18n.t('ongoing') %>.
                  <% else %>
                    <%= I18n.t('over') %>.
                  <% end %>
                <% end %>
        <br>
        <% if @event.tasks.any? %>
          <% if @max == @current %>
            <%= I18n.t('slot_full') %>
          <% else %>
            <% if session[:locale] == "en" %>
              <%= pluralize(@max - @current, I18n.t("need_vol")) %> needed.
            <% else %>
              Cần <%= @max - @current %> <%= I18n.t("need_vol") %>.
            <% end %>
          <% end %> 
        <% end %>
      </h2>
      <h3>
        <% if @event.tasks.any? %>
          <ul>
            <% @event.tasks.each do |t| %>
              <li>
                <%= link_to t.name, t %>
                (<%= "#{t.current_volunteer_number}" %>/<%= "#{t.max_volunteer_number}" %>) (ID: <%=t.id%>)
                <br>

                <% if current_volunteer.core? || current_volunteer.admin? %>
                <h3>
                  <% if t.task_type? %>
                    Volunteer task
                  <% else %>
                    Core team task
                  <% end %> 
                <% end %>
                </h3>
                <div class = "volindex">
                <% if current_volunteer.admin? %>
                  <%= link_to I18n.t('delete'), t, method: :delete,
                                                data: { confirm: "You sure?" }, class: "btn btn-xs btn-info" %>
                  <%= link_to I18n.t('edit'), edit_task_path(t), class: "btn btn-xs btn-info" %>
                <% end %>
                </div>
              </li>
            <% end %>
          </ul>
        <% end %>
      </h3>
    </section>
  </aside>
</div>
</div>