config/routes.rb
Rails.application.routes.draw do
  root 'sesg_page#home'
  
  resources :volunteers
  resources :events
  resources :tasks , only: [:create, :edit, :update, :destroy, :show]
  resources :registers, only: [:create, :destroy]
  resources :notifications, only: [:create, :destroy]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  get     'about'                   => 'sesg_page#about'
  get     'contact'                 => 'sesg_page#contact'
  get     'signup'                  => 'volunteers#new'
  get     'login'                   => 'sessions#new'
  get     'tasks/new/:event_id'     => 'tasks#new'
  get     'help'                    => 'sesg_page#help'
  get     'score_board/:id'         => 'volunteers#score_board'
  get     'admin_history'           => 'admin_histories#new'
  get     'search'                  => 'volunteers#search'
  get     'change_locale/:lang'     => 'sessions#change_locale'
  
  
  post    'reset/volunteers/:id'    => 'volunteers#reset'
  post    'assess'                  => 'registers#update_all'
  post    'appoint/volunteers/:id'  => 'volunteers#appoint'
  post    'login'                   => 'sessions#create'
  
  delete  'logout'                  => 'sessions#destroy'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Volunteer Management Website by SESG - RMIT University Vietnam
  </small>
  <nav>
    <ul>
      <li><%= link_to I18n.t('about'),   about_path %></li>
      <li><%= link_to I18n.t('contact'),   contact_path %></li>
    </ul>
  </nav>
</footer>
 

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div>
    <div id="nav">
    	<div>
      	<% abc = session[:locale] %>
        <% if abc == "en" || abc.nil? %>
          <%= link_to "Tiếng Việt", "/change_locale/vn", class: "btn btn-xs btn-info menubtn"%>
        <% else %>
          <%= link_to "English", "/change_locale/en", class: "btn btn-xs btn-info menubtn"%>
        <% end %>
      </div>
      <!--<section class="si-icons si-icons-easing">-->
      <!--  <span id="showLeftPush" class="si-icon si-icon-hamburger-cross" data-icon-name="hamburgerCross"></span>-->
      <!--</section>-->
      </div><button id="showLeftPush" class= "btn btn-xs btn-info menubtn">Menu</button></div>
      <div>
        <% if (current_volunteer != nil) %>
          <% if (!current_volunteer.admin?) %>
            <button class="dropdown btn btn-xs menubtn">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= I18n.t('notifications') %><b class="caret"></b>
              </a>
              <ul class="dropdown-menu dropdown-menu-right menubtn noti">
                <% if (@notis.size == 0) %>
                  <a>No notifications</a>
                <% else %>
                  <% @notis.each do |n| %>
                      <% if !n.event_id.nil? %>
                        <li>
                        <%= link_to n.content, "/events/#{n.event_id.to_s}" %>
                        </li>
                      <% else %>
                        <li>
                        <%= link_to n.content, "#" %>
                        </li>
                      <% end %>
                  <% end %>
                <% end %>
              </ul>
            </button>
          <% end %>
        <% end %>
      </div>
    </div>
    
    <nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" id="cbp-spmenu-s1">
      <h3><%= image_tag("sesgnoslogan.png", size: "133x70", alt: "SESG Intranet", class: "center-block img-responsive") %></h3>
        <% if !logged_in? %>
        <%= link_to I18n.t('home'), root_path %>
        <% else %>
        <%= link_to I18n.t('home'), root_path %>
        <%= link_to I18n.t('dashboard'), current_volunteer %>
        <% end %>
        <%= link_to I18n.t('help'), help_path %>
        <% if logged_in? %>
          <%= link_to I18n.t('volunteers'), volunteers_path %>
          <%= link_to I18n.t('events'), events_path %>
  
          <% if current_volunteer.admin? %>
            <%= link_to I18n.t('history'), admin_history_path %>
          <% end %>
          
          <h3 style= "font-size: 1.5em;">
            <%= I18n.t('account') %>
          </h3>
          <%= link_to I18n.t('settings'), edit_volunteer_path(current_volunteer) %>
          <%= link_to I18n.t('logout'), logout_path, method: "delete" %>

        <% else %>
          <%= link_to I18n.t('login'), login_path %>
          <%= link_to I18n.t('signup_now'), signup_path %>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body class= "cbp-spmenu-push">
    <%= render 'layouts/header' %>
    <div class="blah">
      <% flash.each do |message_type, message| %>
        <div id="alert" class="container alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>